Fixes #138; Adds routing table according to spec
pokt-network/pocket-js-LEGACY pull request #139
Opened 2020-01-03 06:52 UTC by nymd

One assumption was made: that "maxNodes" should be on a per blockchain basis.

Nodes are stored in a dictionary based on their netID and are limited to the maxNodes per netID.

2020-01-03 14:15 UTC, luyzdeleon requested changes
I appreciate the creativity with the netID's but there are is an issue with it: the routing table is to be able to save nodes to perform dispatches later on, it doesn't matter what chains they support, dispatching is a function inherent to Pocket Nodes, and all of them can execute that function. Also you can add a Public Key property to the node model to identify instead of using service url and netid.

2020-01-03 14:22 UTC, nymd commented
- remove netID as the key for nodes
- max nodes is max nodes, not per blockchain
- add public key property to node model
- change URL to proper type

2020-01-03 15:49 UTC, luyzdeleon commented on src/models/routing.ts
> +    public readNode(publicKey: string) {
Can we add return type to the function? e.g.:
`public readNode(publicKey: string): Node`

2020-01-03 15:49 UTC, luyzdeleon commented on src/models/routing.ts
> +    public readRandomNodes(count: number) {
Add return type to function.

2020-01-03 15:49 UTC, luyzdeleon commented on src/models/routing.ts
> +    public readRandomNode() {
Add return type.

2020-01-03 15:50 UTC, luyzdeleon commented on src/models/routing.ts
> +    public deleteNode(node: Node) {
This might be too much of a personal preference, but I always like returning the deleted objects in `deleteX` functions. If you decide to proceed with this, add the return type.

2020-01-03 15:56 UTC, nymd commented on src/models/routing.ts
> +    public readNode(publicKey: string) {
Forgot about return types in TS!

2020-01-03 15:57 UTC, nymd commented on src/models/routing.ts
> +    public deleteNode(node: Node) {
Hm ok I've never done that; I would tend towards returning a boolean of success/failure if anything

2020-01-03 16:00 UTC, luyzdeleon commented on src/models/routing.ts
> +    public deleteNode(node: Node) {
Cool let's do that then, we need some sort of signal that the node was deleted succesfully. Either that or return `Error | undefined`.

2020-01-07 20:38 UTC, luyzdeleon approved these changes

2020-01-07 21:09 UTC, merged