Issue #133
pokt-network/pocket-js-LEGACY pull request #140
Opened 2020-01-06 16:10 UTC by luyzdeleon

Closes #133

2020-01-06 19:45 UTC, wgarcia4190 approved these changes

2020-01-06 22:23 UTC, nymd requested changes
Requires linting :)

2020-01-06 22:23 UTC, nymd commented on src/utils/key-pair.ts
> +export function validateAddressHex(addressHex: string): Error | undefined {
Is there some point where this data might come in from an untrusted source?  Or a chance someone might enter this data in incorrectly?  An additional regex check for hex-valid characters would add an additional layer of verification in addition to length.

2020-01-06 22:23 UTC, nymd commented on src/utils/key-pair.ts
> +export function validateAddressHex(addressHex: string): Error | undefined {
I can't see how it could be mis-used at this time and do anything except throw the expected error so it is good enough for current usage. However since it does claim to "validate Hex" it might be used in the future with the expectation that it is validating more than just the length.

2020-01-06 22:23 UTC, nymd commented on src/keybase/keybase.ts
> +        if (passphrase.length === 0) {
If we're going to enforce that a passphrase exists, would it be more useful to enforce something about it -- like at least length 5?  a 1 character passphrase might as well be 0 length

2020-01-06 22:23 UTC, nymd commented on src/keybase/keybase.ts
> +    private async unlockAccountFromPersistence(
The spec given in the issue states that the unlocking should have a TTL / expiry.

2020-01-07 20:32 UTC, luyzdeleon commented on src/keybase/keybase.ts
> +    private async unlockAccountFromPersistence(
In the end I left it open ended so developers have the most freedom on how they want to secure their applications.

2020-01-07 20:32 UTC, luyzdeleon commented on src/keybase/keybase.ts
> +        if (passphrase.length === 0) {
This makes sense, but again, developers need to have every option on how they want to secure their applications.

2020-01-07 20:34 UTC, luyzdeleon commented on src/utils/key-pair.ts
> +export function validateAddressHex(addressHex: string): Error | undefined {
The context here is that it's all tied up to the keypair generated by a `ed25519` ECDSA. However I understand the concern and created an issue to address this more generically: https://github.com/pokt-network/pocket-js/issues/143

2020-01-07 21:10 UTC, merged