Issue #137
pokt-network/pocket-js-LEGACY pull request #147
Opened 2020-01-10 19:10 UTC by wgarcia4190

Initial implementation of Session Manager

2020-01-11 04:26 UTC, luyzdeleon requested changes

2020-01-11 04:26 UTC, luyzdeleon commented on src/utils/session-manager.ts
> +            //TODO replace 10 with a configuration property
Why don't we do this in this same PR?

2020-01-12 04:46 UTC, pabelnl commented on src/utils/session-manager.ts
> +    public createSession(header: SessionHeader, node: Node, configuration: Configuration) {
make the function async, return a promise with a boolean indicating if the session was created successfully or and rpcErrorResponse.

2020-01-12 04:46 UTC, pabelnl commented on src/utils/session-manager.ts
> +        throw new TypeError("Session not found")
instead of throwing an Error, return an Error, this will easy the pocket interface, if getSession fails it will create a new session

2020-01-12 05:25 UTC, luyzdeleon commented on src/utils/session-manager.ts
> +    public createSession(header: SessionHeader, node: Node, configuration: Configuration) {
This should return a session object.

2020-01-12 21:45 UTC, pabelnl approved these changes

2020-01-12 21:45 UTC, pabelnl commented on src/utils/session-manager.ts
> +    public createSession(header: SessionHeader, node: Node, configuration: Configuration) {
+ 1 :)

2020-01-12 21:47 UTC, luyzdeleon approved these changes

2020-01-12 21:48 UTC, merged