Issue #146
pokt-network/pocket-js-LEGACY pull request #148
Opened 2020-01-12 22:11 UTC by pabelnl

closes #146

2020-01-12 22:27 UTC, wgarcia4190 requested changes

2020-01-12 22:27 UTC, wgarcia4190 commented on src/models/application-params.ts
> +    public readonly unstakingTime: string;
Please remove the semicolons

2020-01-12 22:27 UTC, wgarcia4190 commented on src/models/block-header.ts
> +    public readonly numTXs: BigInt;
Please remove the semicolons

2020-01-12 22:27 UTC, wgarcia4190 commented on src/models/output/bond-status.ts
> +        return BondStatus.bonded;
Looks like we had an issue during a merge

2020-01-13 19:39 UTC, luyzdeleon approved these changes

2020-01-13 19:43 UTC, wgarcia4190 approved these changes

2020-01-13 19:50 UTC, merged