Pocket js core 0.0.1
pokt-network/pocket-js-LEGACY pull request #19
Opened 2019-03-12 15:45 UTC by pabelnl

created classes Pocket, Configuration, Blockchain, Relay, Dispatch, Node, Wallet.

implemented retrieve nodes from dispatcher, create relay, send relay.

Closes #5 #6 #7

2019-03-12 18:21 UTC, luyzdeleon requested changes

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/core.js
> +    this.dispatchNodeURL = "http://dispatch.staging.pokt.network";
Can we define these as constants and read from there instead of using class variables?

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/core.js
> +    this.maxNodes = maxNodes || 5;
Can we document defaults?

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/core.js
> +    if (opts["devID"] == null || opts["networkName"] == null || opts["netIDs"] == null || opts["version"] == null) {
Can we access properties via `.property` notation? E.g. `opts.devID`

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/core.js
> +      opts["netIDs"].forEach(element => {
See above

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/core.js
> +      this.configuration.relay = new Relay(blockchain, netID, version, data, devID, this.configuration);
Why is the relay a property of the configuration?

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/core.js
> +          nodes.push(element);
Shouldn't this list be a list of `Node` instances?

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/core.js
> +        throw new Error("No nodes are available for required specifications: " +
Why `throw` if the list is empty?

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/core.js
> +  async sendRelay(callback) {
Shouldn't this receive a `Relay` instance as an argument?

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/core.js
> +      if (this.configuration.relay == null) {
?

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/core.js
> +        if (!this.configuration.relay.hasOwnProperty(property)) {
`Relay` needs a method called `isValid` to avoid doing these checks manually.

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/core.js
> +        if (element.netID == netID && element.network == network && element.version == version) {
`Node` needs a `isValid` method.

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/core.js
> +      var response = await node.sendRelay();
Pass the `Relay` as an argument to `sendRelay`

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/core.js
> +      if (response instanceof Error == false) {
I think there's a better way to check for this than `instanceof`

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/core.js
> +          callback(false);
Pass an error to the callback, not a bool

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/models/dispatch.js
> +    this.blockchainsJSON = function () {
Don't declare functions this way, declare a class `function` and retrieve whatever data you need from the class attributes.

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/models/dispatch.js
> +      if (response.status == 200 && response.data != null) {
Check if response is null?

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/models/dispatch.js
> +  parseDispatchResponse(obj) {
Rename `obj` to `response`

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/models/dispatch.js
> +        // Iterate thruth the array for different networks results
`through`

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/models/dispatch.js
> +            new Error("Failed to parse Node object")
Let's not throw an error here, but ignore that one and let the iteration continue.

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/models/dispatch.js
> +        var objKey = Object.keys(obj);
Rename `objKey` to `keys`

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/models/dispatch.js
> +          return new Error("Failed to parsed service nodes with error: Node information is missing 1 or more params.");
Return the keys array in the error message, use `JSON.stringify`

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/models/node.js
> +    async sendRelay(callback) {
Pass a `Relay` as an argument

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/models/node.js
> +        this.relay = null;
Remove this attribute, see below.

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/models/node.js
> +        this.ipPort = "http://"+ipPort;
Don't append http manually, or at least check if the variable already has that prefix.

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/models/node.js
> +            var response = await axiosInstance.post(this.relay.configuration.relayPath, {
If you passed the `Relay` as an argument, you could do `relay.toJSON` instead of having to build this object manually.

2019-03-12 18:21 UTC, luyzdeleon commented on packages/core/src/models/relay.js
> +class Relay {
Create a `toJSON` convenience method for relay serialization.

2019-03-13 18:48 UTC, pabelnl commented on packages/core/src/core.js
> +          nodes.push(element);
it is

2019-03-14 13:26 UTC, pabelnl commented on packages/core/src/core.js
> +      if (response instanceof Error == false) {
this is one of the more elegant ways to check if error type

2019-03-14 17:29 UTC, luyzdeleon requested changes

2019-03-14 17:29 UTC, luyzdeleon commented on packages/core/src/core.js
> +      throw error;
Don't catch just to throw.

2019-03-14 17:29 UTC, luyzdeleon commented on packages/core/src/core.js
> +      throw error;
Don't catch just to throw

2019-03-14 17:29 UTC, luyzdeleon commented on packages/core/src/core.js
> +        throw new Error("Failed to filter nodes. List is empty.");
I don't feel like we should throw errors in this function, just return null if a node is not found, let the caller resolve that any way they want.

2019-03-14 17:29 UTC, luyzdeleon commented on packages/core/src/core.js
> +      throw new Error("Failed to filter nodes with error: " + error);
Just return null.

2019-03-14 17:29 UTC, luyzdeleon commented on packages/core/src/core.js
> +        throw new Error("Report is null");
Wouldn't it better to return an error like you're doing in the other function? Also call the callback with the error.

2019-03-14 17:29 UTC, luyzdeleon commented on packages/core/src/core.js
> +        throw new Error("Report is missing a property: " + property);
Same as above.

2019-03-14 17:29 UTC, luyzdeleon commented on packages/core/src/core.js
> +      throw new Error("Failed to send report with error: " + error);
call the callback with the error? or return it?

2019-03-14 17:29 UTC, luyzdeleon commented on packages/core/src/core.js
> +        throw new Error("Relay is null or data field is missing");
Same as above.

2019-03-14 17:29 UTC, luyzdeleon commented on packages/core/src/core.js
> +        throw new Error("Relay is missing a property: " + property);
Same as above.

2019-03-14 17:29 UTC, luyzdeleon commented on packages/core/src/core.js
> +        throw new Error("Node is empty;");
Same as above.

2019-03-14 17:29 UTC, luyzdeleon commented on packages/core/src/core.js
> +      throw new Error("Failed to send relay with error: " + error)
Same as above.

2019-03-14 17:29 UTC, luyzdeleon commented on packages/core/src/core.js
> +      return new Error("Failed to retrieve service nodes with error: " + error);
Same as above.

2019-03-14 17:29 UTC, luyzdeleon commented on packages/core/src/core.js
> +          callback(true);
Returning true is not helpful, return the nodes.

2019-03-14 17:29 UTC, luyzdeleon commented on packages/core/src/models/dispatch.js
> +      return new Error("Failed to retrieve service nodes with error: " + err);
Call the callback with the error and return Error or null.

2019-03-14 17:29 UTC, luyzdeleon commented on packages/core/src/models/dispatch.js
> +          new Error("Failed to parse Node object")
?

2019-03-14 17:29 UTC, luyzdeleon commented on packages/core/src/models/dispatch.js
> +          return new Error("Failed to parsed service nodes with error: Node information is missing 1 or more params: "+ JSON.stringify(keysArr));
Don't return errors in this function, throw them.

2019-03-14 17:29 UTC, luyzdeleon commented on packages/core/src/models/dispatch.js
> +      return new Error("Failed to parsed service nodes with error: " + error);
Don't return errors in this function, throw them.

2019-03-14 17:29 UTC, luyzdeleon commented on packages/core/src/models/node.js
> +                  throw new Error("Failed to send relay with error: " + response.data);
Return the error like you're doing in the catch?

2019-03-14 20:04 UTC, luyzdeleon requested changes

2019-03-14 20:04 UTC, luyzdeleon commented on packages/core/src/core.js
> +        if (element.netID == netID && element.network == network && element.version == version) {
`Node` needs a isValid method and it can be used here to know if the nodes are valid.

2019-03-14 20:04 UTC, luyzdeleon commented on packages/core/src/core.js
> +      throw new Error("Failed to send report with error: " + error);
Still missing this part.

2019-03-14 23:42 UTC, luyzdeleon approved these changes

2019-03-14 23:42 UTC, luyzdeleon commented on packages/core/src/core.js
> +    this.relay = null;
Remove this.

2019-03-18 12:44 UTC, luyzdeleon requested changes

2019-03-18 12:44 UTC, luyzdeleon commented on packages/core/tests/coreTest.js
> +        expect(result).to.equal(true);
Shouldn't the result of a call to `retrieveNodes` be a list of nodes?

2019-03-18 12:44 UTC, luyzdeleon commented on packages/core/tests/coreTest.js
> +        var pocket = new Pocket(opts);
Why 2 instances?

2019-03-18 12:44 UTC, luyzdeleon commented on packages/core/tests/coreTest.js
> +            netIDs: [40],
Clearly illustrate in the test what's being done wrong. Either with a comment, or a variable name or something that indicates to the reader that this is a wrong NET ID

2019-03-18 12:44 UTC, luyzdeleon commented on packages/core/tests/coreTest.js
> +        expect(result).to.equal(false);
Shouldn't this result be a list of nodes?

2019-03-18 12:44 UTC, luyzdeleon commented on packages/core/tests/coreTest.js
> +        expect(result).to.equal(true);
Shouldn't this result be a list of nodes?

2019-03-18 12:44 UTC, luyzdeleon commented on packages/core/tests/coreTest.js
> +        var relay = pocket.createRelay("ETH", pocket.configuration.blockchains[0].NetID, version, data, pocket.configuration.devID);
`netID` is misspelled as `NetID`

2019-03-18 12:44 UTC, luyzdeleon commented on packages/core/tests/coreTest.js
> +        expect(response).to.be.a('string');
Why should an `Error` be a string?

2019-03-18 12:44 UTC, luyzdeleon commented on packages/core/tests/coreTest.js
> +        var relay = pocket.createRelay("ETH", 10, version, data, pocket.configuration.devID);
If the pocket instance already has a configuration property, and that configuration contains the devID, why do we pass it again as a parameter in this call?

2019-03-18 12:44 UTC, luyzdeleon commented on packages/core/tests/coreTest.js
> +        expect(result).to.equal(true);
Shouldn't this result be a list of nodes?

2019-03-18 12:44 UTC, luyzdeleon commented on packages/core/tests/coreTest.js
> +        expect(node).to.be.an('object');
Shouldn't we check if the node is an instance of `Node` ?

2019-03-18 12:44 UTC, luyzdeleon commented on packages/core/tests/coreTest.js
> +    it('should fail to send a report of a node to the Node Dispatcher with no Node IP', async () => {
This tests didn't ran locally for me.

2019-03-18 12:44 UTC, luyzdeleon commented on packages/core/tests/coreTest.js
> +        expect(node).to.be.an('object');
Let's check if it's instanceof `Node`

2019-03-18 12:44 UTC, luyzdeleon commented on packages/core/tests/coreTest.js
> +        expect(result).to.equal(true);
Shouldn't this result be a list of nodes?

2019-03-18 12:44 UTC, luyzdeleon commented on packages/core/tests/coreTest.js
> +        expect(response).to.not.be.an.instanceof(Error);
In this case shouldn't the response be an instance of Error, since that's what you're testing?

2019-03-18 14:00 UTC, pabelnl commented on packages/core/tests/coreTest.js
> +        expect(result).to.equal(true);
no, returns true or false because the list is saved into the configuration of the pocket instance as we discussed last week :)

2019-03-18 19:29 UTC, pabelnl commented on packages/core/tests/coreTest.js
> +        var relay = pocket.createRelay("ETH", pocket.configuration.blockchains[0].NetID, version, data, pocket.configuration.devID);
the blockchains are stored as JSON with the key as the request requires as per the documentation.

2019-03-18 19:32 UTC, pabelnl commented on packages/core/tests/coreTest.js
> +        expect(response).to.be.a('string');
the test is 'should send a relay to a node in the network', it is not expecting an error but a string.

expect(response).to.not.be.an.instanceof(Error); <--- if is an error it fails, if not it will continue.
expect(response).to.be.a('string'); <--- it will verify is an string because the response is an string when successful

2019-03-18 19:33 UTC, pabelnl commented on packages/core/tests/coreTest.js
> +        var relay = pocket.createRelay("ETH", 10, version, data, pocket.configuration.devID);
You can have multiple blockchains in the configuration but the relay should be for 1 blockchain.

2019-03-18 19:36 UTC, luyzdeleon commented on packages/core/tests/coreTest.js
> +        var relay = pocket.createRelay("ETH", 10, version, data, pocket.configuration.devID);
But the DevID is the one thing that doesn't change.

2019-03-18 19:38 UTC, luyzdeleon commented on packages/core/tests/coreTest.js
> +        var relay = pocket.createRelay("ETH", pocket.configuration.blockchains[0].NetID, version, data, pocket.configuration.devID);
But the documentation also says it's case insensitive and it is in the style guide of javascript to have properties be camel case: `netID`

2019-03-18 23:44 UTC, pabelnl commented on packages/core/tests/coreTest.js
> +        var relay = pocket.createRelay("ETH", pocket.configuration.blockchains[0].NetID, version, data, pocket.configuration.devID);
You are right, did the change on the .json method so we can use netID as in the other areas of the code.

2019-03-18 23:51 UTC, pabelnl commented on packages/core/tests/coreTest.js
> +        var relay = pocket.createRelay("ETH", 10, version, data, pocket.configuration.devID);
Sorry, I misunderstood devID with netID, doing the change.

2019-03-19 13:03 UTC, merged