Updating Pocket Interface initialization
pokt-network/pocket-js-LEGACY pull request #222
Opened 2020-02-14 13:12 UTC by wgarcia4190

Close #220
Close #221

2020-02-14 14:41 UTC, luyzdeleon requested changes

2020-02-14 14:41 UTC, luyzdeleon commented on src/pocket.ts
> +    throw new Error("You need to specify the RPCProvider at least once")
Let's try not to throw errors unless it's a constructor.

2020-02-14 14:41 UTC, luyzdeleon commented on src/pocket.ts
> +  public rpc(rpcProvider?: IRPCProvider): RPC {
Return type should be RPC | undefined.

2020-02-20 23:40 UTC, pabelnl requested changes

2020-02-20 23:40 UTC, pabelnl commented on src/pocket.ts
> +  private innerRpc?: RPC
why is it called innerRpc?

2020-02-20 23:40 UTC, pabelnl commented on src/pocket.ts
>      this.sessionManager = new SessionManager(this.routingTable, store)
Add this sessionManager initializer to the try and catch blocks

2020-02-20 23:40 UTC, pabelnl commented on src/pocket.ts
> +
Add documentation for the function following the standards, params/return/memberOf

2020-02-20 23:40 UTC, pabelnl commented on src/routing-table/routing-table.ts
>          "Routing table must be initialized with at least one node."
Update to "Dispatch node"

2020-02-20 23:40 UTC, pabelnl commented on tests/src/integration/pocket.spec.ts
>  const dispatchNodeJSON = "{\"address\":\"189ceb72c06b99e15a53fd437b81d4500f7a01f1\",\"public_key\":\"1839f4836f22d438692355b2ee34e47d396f6eb23b423bf3a1e623137ddbf7e3\",\"jailed\":false,\"status\":2,\
Instead of using a full node object, just create the constant for the URL of that node, so the tests seem more simple.

2020-02-20 23:40 UTC, pabelnl commented on tests/src/integration/rpc/query.spec.ts
>  const node01 = new Node(addressHex, applicationPublicKey, false, BondStatus.bonded, BigInt(100), env.getPOKTRPC(), blockchains)
Same here, use the serviceURL instead of creating the whole node

2020-02-21 12:43 UTC, wgarcia4190 commented on src/pocket.ts
> +  private innerRpc?: RPC
this is because we have a get function called rpc, so we cannot have a property with the same name. If we try to use the same name we are going to face a Duplicate identifier error

2020-02-21 12:43 UTC, wgarcia4190 commented on src/pocket.ts
> +  private innerRpc?: RPC
Let me know if you have any suggestion about this

2020-02-21 13:06 UTC, pabelnl commented on src/pocket.ts
> +  private innerRpc?: RPC
solved

2020-02-21 13:10 UTC, pabelnl approved these changes

2020-02-21 19:37 UTC, luyzdeleon approved these changes

2020-02-21 19:38 UTC, merged