Issue #232
pokt-network/pocket-js-LEGACY pull request #240
Opened 2020-03-10 21:50 UTC by pabelnl

Closes #232

2020-03-10 22:21 UTC, nymd requested changes
No real changes requested, just some clarification and comments, thanks.

2020-03-10 22:21 UTC, nymd commented on src/transactions/i-transaction-sender.ts
>          chainId: string,
The file rpc/models/block-header.ts uses the camelcase of "chainID" instead of "chainId"

I personally prefer chainID but I'm fine either way as long as we are consistent everywhere.

2020-03-10 22:21 UTC, nymd commented on src/transactions/models/std-sign-doc.ts
> -     * @param {BigInt} entropy - Random int64.
For my benefit, why is this changed to a string?  Can we add a comment there as to why so the next noob like me isn't confused why an int64 is stored as a string, thanks.

2020-03-10 22:40 UTC, pabelnl commented on src/transactions/models/std-sign-doc.ts
> -     * @param {BigInt} entropy - Random int64.
the transaction-sender doesn't receive the entropy as a param anymore, it is always generated, but we changed to string because of some issues while calling the marshalPosmintTx that is related to the amino-js dependency, it wasn't accepting the BigInt, only numbers, and strings. We can safely save a BigInt number representation inside a string, the library works fine with it.

2020-03-11 13:33 UTC, luyzdeleon approved these changes

2020-03-11 13:51 UTC, nymd approved these changes

2020-03-11 14:32 UTC, merged