#238 Adding entities necessary to perform a challenge operation
pokt-network/pocket-js-LEGACY pull request #243
Opened 2020-03-16 09:29 UTC by wgarcia4190

2020-03-16 13:03 UTC, pabelnl submitted a review, later dismissed
Great job!

2020-03-16 18:59 UTC, nymd requested changes
Can you submit the tests surrounding this with the PR? Thanks!

2020-03-16 18:59 UTC, nymd commented on src/rpc/models/input/challenge-request.ts
> +            this.address.length > 0)
I'd like to see us move towards stricter validations; like in the utils file
> export function validateAddressHex

2020-03-16 18:59 UTC, nymd commented on src/rpc/models/input/majority-response.ts
> +                jsonObject.majority_responses.forEach((relay: any) => {
Anthony points out that this can be only two responses:

type challengeProofInvalidData struct {
	MajorityResponses [2]relayResponse
	MinorityResponse  relayResponse
}

Maybe we should limit/check the size of the array?

2020-03-16 18:59 UTC, nymd commented on src/rpc/models/input/request-hash.ts
> +export class RequestHash {
Anthony requests that we not stringify the http headers in the request hash as it was causing issues on their side.

2020-03-16 21:17 UTC, andrewnguyen22 requested changes

2020-03-16 21:17 UTC, andrewnguyen22 commented on src/rpc/models/input/request-hash.ts
> +export class RequestHash {
Responses are not relay objects too! Please ensure the entire Relay Response object is in there

2020-03-17 12:57 UTC, wgarcia4190 commented on src/rpc/models/input/majority-response.ts
> +                jsonObject.majority_responses.forEach((relay: any) => {
understood

2020-03-17 12:58 UTC, wgarcia4190 commented on src/rpc/models/input/challenge-request.ts
> +            this.address.length > 0)
Sure thing, I don't know if you want me to do this in this PR or if you want to create a new ticket for it

2020-03-17 13:01 UTC, wgarcia4190 commented on src/rpc/models/input/request-hash.ts
> +export class RequestHash {
got it. Thanks

2020-03-17 13:04 UTC, wgarcia4190 commented
> Can you submit the tests surrounding this with the PR? Thanks!

I usually try to add the tests in another PR, to avoid having big PR's, but sure I can add the tests in this PR too

2020-03-17 13:09 UTC, nymd commented on src/rpc/models/input/challenge-request.ts
> +            this.address.length > 0)
In this one is fine since this is a new file in this commit, no problem.

2020-03-17 13:10 UTC, wgarcia4190 commented on src/rpc/models/input/challenge-request.ts
> +            this.address.length > 0)
understood

2020-03-19 15:27 UTC, nymd approved these changes

2020-03-19 16:12 UTC, nymd requested changes

2020-03-19 16:12 UTC, nymd commented on src/rpc/models/input/relay.ts
> +     * Creates a MajorityResponse object using a JSON string
Comments have copypasta; thanks

2020-03-19 16:12 UTC, nymd commented on src/rpc/models/input/relay.ts
> +     * Creates a JSON object with the MajorityResponse properties
Here as well

2020-03-19 16:13 UTC, andrewnguyen22 requested changes

2020-03-19 16:13 UTC, andrewnguyen22 commented on src/utils/validator.ts
> +            return new Error("Invalid majority request. The amount of relays needs to be bigger than 0 and lower than 3")
this actually needs to be strictly 2
```
request.majorityResponse.relays.length !== 2:
  return new Error("...")
```

2020-03-19 19:26 UTC, wgarcia4190 commented on src/utils/validator.ts
> +            return new Error("Invalid majority request. The amount of relays needs to be bigger than 0 and lower than 3")
Thanks

2020-03-20 00:15 UTC, nymd submitted a review, later dismissed

2020-03-20 17:35 UTC, andrewnguyen22 requested changes

2020-03-20 17:35 UTC, andrewnguyen22 commented on src/rpc/models/input/request-hash.ts
> +            payload: this.payload.toJSON(),
```
public toJSON() {
    return {
      data: this.data,
      headers: this.headers,
      method: this.method,
      path: this.path
    }
  }
```
Should ignore headers for Request Hash see @nymd previous comment

2020-03-20 18:33 UTC, nymd submitted a review, later dismissed

2020-03-20 19:43 UTC, nymd approved these changes

2020-03-21 00:16 UTC, nymd approved these changes

2020-03-21 00:16 UTC, merged