Issue #239
pokt-network/pocket-js-LEGACY pull request #250
Opened 2020-03-30 15:15 UTC by luyzdeleon

Closes #239
Closes #231

2020-03-30 16:44 UTC, nymd commented
Waiting on Pabel's additions

2020-03-31 14:20 UTC, nymd requested changes

2020-03-31 14:20 UTC, nymd commented on README.md
> +const pocketInstance = new Pocket(configuration, rpcProvider)
This is out of date.

  /**
   * Creates an instance of Pocket.
   * @param {URL} dispatchers - Array holding the initial dispatcher url(s).
   * @param {IRPCProvider} rpcProvider - Provider which will be used to reach out to the Pocket Core RPC interface.
   * @param {Configuration} configuration - Configuration object.
   * @param {IKVStore} store - Save data using a Key/Value relationship. This object save information in memory.
   * @memberof Pocket
   */

2020-03-31 14:20 UTC, nymd commented on README.md
> +const configuration = new Configuration(5, 60000, 1000000)
This is out of date.

  /**
   * Stores multiple properties used to interact with the Pocket Network.
   * @constructor
   * @param {number} maxDispatchers - (optional) Maximun amount of dispatchers urls to stored in rounting table, default 0.
   * @param {number} maxSessions - (optional) Maximun amount of sessions to stored for the session manager, default 0.
   * @param {number} maxConsensusNodes - (optional) Maximun amount of nodes for local consensus, mandatory ODD number, default 0.
   * @param {number} requestTimeOut - (optional) Maximun timeout for every request in miliseconds, default 0.
   * @param {boolean} acceptDisputedResponses - (optional) Accept or reject responses based on having a full consensus, default false.
   * @memberof Configuration
   */

2020-03-31 14:20 UTC, nymd commented on src/config/configuration.ts
> +  public readonly acceptDisputedResponses: boolean = false
I know this is really picky but can we keep variables and comments in the same order? I find it makes it easier to read.

2020-03-31 14:20 UTC, nymd commented on src/config/configuration.ts
> +   * @param {number} maxConsensusNodes - (optional) Maximun amount of nodes for local consensus, mandatory ODD number, default 0.
why is this called "max" -- it implies that it may use less than this.

As a developer reading this for the first time I would wonder if it would use fewer than what I specified. Maybe a better name would be "consensusRequired" or something like that.

2020-03-31 14:20 UTC, nymd commented on src/config/configuration.ts
> +    if (maxConsensusNodes % 2 === 1 || maxConsensusNodes === 0) {
What happens if a dev specifies more than the network offers?  Normally we offer 5, what if the dev says, give me 99?

I'm guessing it might not matter and the system would just use the 5.

2020-03-31 14:20 UTC, nymd commented on src/pocket.ts
> +      } else if (consensusRelayResponse.majorityResponse !== undefined && consensusRelayResponse.minorityResponse !== undefined){
How does this handle an edge case if you get two minority responses?

5 node consensus requested.
3 agree, 2 have different responses.

Are challenges opened against both offenders?

3 node consensus requested, all 3 return different results. Do all 3 get challenged?

2020-03-31 14:20 UTC, nymd commented on src/config/configuration.ts
> +    if (maxConsensusNodes % 2 === 1 || maxConsensusNodes === 0) {
Nevermind, I see the answer below!  It throws.

2020-03-31 14:27 UTC, pabelnl commented on src/config/configuration.ts
> +   * @param {number} maxConsensusNodes - (optional) Maximun amount of nodes for local consensus, mandatory ODD number, default 0.
True, good catch, will it be better "consensusNodes" or "consensusNodesCount"? @luyzdeleon @wgarcia4190

2020-03-31 14:29 UTC, pabelnl commented on src/pocket.ts
> +      } else if (consensusRelayResponse.majorityResponse !== undefined && consensusRelayResponse.minorityResponse !== undefined){
As per what Wilson talked with Andrew, only 1 response should be in the minority and 2 in the majority. @wgarcia4190 can you elaborate a little on this?

2020-03-31 14:31 UTC, nymd commented on src/config/configuration.ts
> +   * @param {number} maxConsensusNodes - (optional) Maximun amount of nodes for local consensus, mandatory ODD number, default 0.
consensusNodeCount -- without the 's' -- sounds good

2020-03-31 14:35 UTC, nymd commented on src/pocket.ts
> +      } else if (consensusRelayResponse.majorityResponse !== undefined && consensusRelayResponse.minorityResponse !== undefined){
That makes sense as b-dev wants them one at a time; 

In the case that 3 agree and 2 disagree, I think challenges should be launched against the two disagreers. Or maybe at that point the relay is too disputed to accept at all?

I will ask Andrew what he thinks should happen with this.

2020-03-31 14:35 UTC, nymd commented on src/pocket.ts
> +      } else if (consensusRelayResponse.majorityResponse !== undefined && consensusRelayResponse.minorityResponse !== undefined){
Thoughts @luyzdeleon ?

2020-03-31 15:24 UTC, nymd commented on src/pocket.ts
> +      } else if (consensusRelayResponse.majorityResponse !== undefined && consensusRelayResponse.minorityResponse !== undefined){
Andrew says if it comes back in either of those two scenarios, with more than 1 disputed response, toss the whole thing and throw an error.

2020-03-31 16:03 UTC, luyzdeleon commented on src/rpc/models/output/consensus-relay-response.ts
> +    if (minorityResponse.length > 0 && majorityResponse.length > 0) {
Because we just wanna capture the case of having 1 node in disagreement with the rest, we will change this to:
`if (minorityResponse.length === 1 && majorityResponse.length > 0) {`.

2020-03-31 16:48 UTC, pabelnl approved these changes

2020-03-31 16:49 UTC, nymd approved these changes

2020-03-31 16:49 UTC, merged