Issue #392
pokt-network/pocket-js-LEGACY pull request #396
Opened 2021-04-22 21:47 UTC by pabelnl

closes #392

- Changed default values in Configuration for maxDispatchers to 50 and maxSessionRefreshRetries to 1
- Removed unnecessary code for requestCurrentSession, renamed the same metho to requestNewSession, added check for deleteDispatcher flow on the session manager
- Improved addDispatcher and removeDispatcher, added check for readRandomDispatcher
- AddDispatcher and removeDispatcher now returns a boolean, now only the constructor throw errors
- Updated session-manager and routing tests

2021-04-23 14:14 UTC, wgarcia4190 approved these changes, later dismissed

2021-04-23 17:06 UTC, luyzdeleon requested changes

2021-04-23 17:06 UTC, luyzdeleon commented on src/routing-table/routing-table.ts
> +    if (dispatchers.length > this.configuration.maxDispatchers && this.configuration.maxDispatchers > 0) {
I'm thinking now maybe we shouldn't allow for `maxDispatchers` to be 0 and avoid unbounded lists.

2021-04-23 17:06 UTC, luyzdeleon commented on src/session/session-manager.ts
> +    } else if(this.routingTable.dispatchersCount > 0) {
Isn't this a function?

2021-04-23 17:06 UTC, luyzdeleon commented on src/routing-table/routing-table.ts
> +  public readDispatcher(url: URL): Node | Error {
This function should get called `getDispatcher`

2021-04-23 17:06 UTC, luyzdeleon commented on src/routing-table/routing-table.ts
> +  public readRandomDispatchers(count: number): URL[] | Error {
This function should be called `getRandomDispatcher`

2021-04-23 17:06 UTC, luyzdeleon commented on tests/src/unit/routing-table/routing.spec.ts
> +        it('should not allow more than the max number of nodes per blockchain to be added to the routing table', () => {
This should read `it should not allow to add more than the maxDispatchers configuration variable number of entries into the routing table.`

2021-04-23 17:06 UTC, luyzdeleon commented on tests/src/unit/routing-table/routing.spec.ts
> +            expect(readDispatcher).to.be.an.instanceof(URL)
This test is wrongly designed, to fully proof randomness, you should insert multiple dispatchers and expect "random" results.

2021-04-23 17:06 UTC, luyzdeleon commented on tests/src/unit/routing-table/routing.spec.ts
> +            expect(dispatchers[2]).to.be.an.instanceof(URL)
Same as above, but with a list.

2021-04-23 17:06 UTC, luyzdeleon commented on tests/src/unit/routing-table/routing.spec.ts
> +        it('should fail to read a specific dispatcher from the routing table due to non-existing dispatcher on the list', () => {
If URL entries in the routing table are expected to be valid fully formed URL's, the test should be done in the `addDispatcher`, not reading from it.

2021-04-23 17:08 UTC, luyzdeleon commented
PR is also lacking documentation from how the full Session Manager workflow works and how the Routing table works.

2021-04-23 17:28 UTC, pabelnl commented on src/routing-table/routing-table.ts
> +    if (dispatchers.length > this.configuration.maxDispatchers && this.configuration.maxDispatchers > 0) {
Totally agree, I was thinking about limiting to 1,000 and let know on the documentation that the bigger the list the performance can be impacted, but as per the latest tests with this version the CPU usage is lower than expected with `maxDispatchers` to 0

2021-04-23 17:28 UTC, pabelnl commented on src/session/session-manager.ts
> +    } else if(this.routingTable.dispatchersCount > 0) {
is a get function

2021-04-23 18:19 UTC, pabelnl commented on src/routing-table/routing-table.ts
> +  public readDispatcher(url: URL): Node | Error {
got it

2021-04-23 18:19 UTC, pabelnl commented on src/routing-table/routing-table.ts
> +  public readRandomDispatchers(count: number): URL[] | Error {
got it

2021-04-23 18:29 UTC, pabelnl commented on tests/src/unit/routing-table/routing.spec.ts
> +            expect(dispatchers[2]).to.be.an.instanceof(URL)
if you see on line 87, I do a for loop to add multiple dispatchers to the routing table, but I will change the expect to
`expect(dispatchers.length).to.be.greaterThanOrEqual(3)`

2021-04-23 19:02 UTC, pabelnl commented on tests/src/unit/routing-table/routing.spec.ts
> +        it('should fail to read a specific dispatcher from the routing table due to non-existing dispatcher on the list', () => {
The fail scenario is for the `getDispatcher()` function, we are expecting it to fail since the specified dispatcher doesn't exist on the routing table.

`        it('should fail to read an specific dispatcher from the routing table due to non-existing dispatcher on the list', () => {
            const badDispatcher = new URL("http://baddispatcher:8081")

            const configuration = getConfig()
            const routing = new RoutingTable([dispatcher], configuration, store)
            
            const dispatcherOrError = routing.getDispatcher(badDispatcher)
            expect(dispatcherOrError).to.be.an.instanceof(Error)
        }).timeout(0)`

2021-04-23 20:44 UTC, luyzdeleon commented on src/routing-table/routing-table.ts
> +    if (dispatchers.length > this.configuration.maxDispatchers && this.configuration.maxDispatchers > 0) {
But still, the risk of it being unbounded, could end up being something that bites us in the ass in the future, better safe than sorry.

2021-04-23 20:44 UTC, luyzdeleon commented on src/session/session-manager.ts
> +    } else if(this.routingTable.dispatchersCount > 0) {
Can you call it fine with this syntax?

2021-04-23 20:45 UTC, luyzdeleon commented on tests/src/unit/routing-table/routing.spec.ts
> +        it('should fail to read a specific dispatcher from the routing table due to non-existing dispatcher on the list', () => {
Ahhh it doesn't exist, I thought we were checking well formatted URL's, got it.

2021-04-23 21:01 UTC, pabelnl commented on src/routing-table/routing-table.ts
> +    if (dispatchers.length > this.configuration.maxDispatchers && this.configuration.maxDispatchers > 0) {
I will limit it to 1000 then

2021-04-23 21:09 UTC, pabelnl commented on src/session/session-manager.ts
> +    } else if(this.routingTable.dispatchersCount > 0) {
yes sir

2021-04-26 19:20 UTC, luyzdeleon commented on src/routing-table/routing-table.ts
> +    if (dispatchers.length > this.configuration.maxDispatchers && this.configuration.maxDispatchers > 0) {
Where are we limiting it to 1000?

2021-04-26 19:24 UTC, luyzdeleon reviewed
Where are we limiting maxDispatchers to 1000?

2021-04-26 19:26 UTC, pabelnl commented on src/routing-table/routing-table.ts
> +    if (dispatchers.length > this.configuration.maxDispatchers && this.configuration.maxDispatchers > 0) {
I changed the configuration class to check for min and max allowed value for multiple properties, the thing is that I will include it in another PR since It gets new tests too.

2021-04-26 19:30 UTC, luyzdeleon approved these changes

2021-04-26 19:30 UTC, merged