Pocket Core improvements
pokt-network/pocket-js-LEGACY pull request #43
Opened 2019-03-24 01:50 UTC by pabelnl

removed relay property from Pocket, added relay data checks for json to stringify

2019-03-24 17:30 UTC, luyzdeleon requested changes

2019-03-24 17:30 UTC, luyzdeleon commented on packages/core/src/core.js
> +    data = JSON.stringify(data);
This should be an else: 

`return  new Relay(blockchain, netID, JSON.stringify(data), this.configuration);`

2019-03-24 17:30 UTC, luyzdeleon commented on packages/core/src/core.js
> +          callback(new Error("Node is empty;"));
Change `;` to `.`

2019-03-24 17:30 UTC, luyzdeleon commented on packages/core/src/models/wallet.js
> +	constructor(address, privateKey, network, subnetwork, data) {
Change subnetwork to netID or networkID

2019-03-25 00:16 UTC, pabelnl commented on packages/core/src/core.js
> +    data = JSON.stringify(data);
no need to encapsulate in an else, the previous statement already does a return even if is an error or Relay.

2019-03-25 00:21 UTC, luyzdeleon commented on packages/core/src/core.js
> +    data = JSON.stringify(data);
Yeah but no need to reassign the data variable to just return it in the next line, agreed with the else.

2019-03-25 03:11 UTC, luyzdeleon approved these changes

2019-03-25 12:20 UTC, merged